function first_GUI(wells, exp_grp_num, wells_tot_num, plate)


scrnsz=get(0,'ScreenSize');
janela=figure('Name','Start defining your experimental groups','NumberTitle','off','Position',[1,1,scrnsz(3)*.65,scrnsz(4)],'color','w');
set(findobj(janela),'Units','Normalized');

h_val = .9/(exp_grp_num);

for ep=1:exp_grp_num;

    %MAke text for EXPERIMENTAL GROUP wells
    exp_grp_text{ep} = uibuttongroup(janela,'Visible','on',...
                  'Position',[.01 1-h_val .45 .9/(exp_grp_num)]);
                  %'SelectionChangedFcn',@bselection
          
              
    set (0, 'DefaultUIControlFontSize', 12-(0.3*exp_grp_num));
                  uicontrol(exp_grp_text{ep},...
                      'Style','text',...
                      'String', ['Describe your "Experimental Group #' num2str(ep) '":'],...
                      'ForegroundColor',[1 0 .3],...
                      'Units', 'normalized',...
                      'Position',[-.1 .75 1 .25]);
                  
    descr_ans{ep} = uicontrol(exp_grp_text{ep},'Style','edit',...
                  'String',['Experimental Group #' num2str(ep)],...
                  'Units', 'normalized',...
                  'Position',[.1 .6 .8 .25],...
                  'Tag', ['' ep ''],...
                  'BackgroundColor',[.85 .85 .85],...
                  'HandleVisibility','off');
            %expDesc{ep} = descr_ans{ep}.String;
            %assignin('base','expDesc', expDesc);         % save to base
              
         
         set (0, 'DefaultUIControlFontSize', 9-(0.3*exp_grp_num));

              
              for pA = 1:length(plate);
   plates_ans(pA) = uicontrol(exp_grp_text{ep},'Style','radiobutton',...
                  'String', ['Plate: "' plate{pA} '"'],...
                  'Value', 0,...
                  'Units', 'normalized',...
                  'Position',[.1 .55-(.15*pA) .6 .05],...
                  'Tag', ['' ep ''],...
                  'BackgroundColor',[.85 .85 .85],...
                  'HandleVisibility','on');
              end;
%               plates_ans(ep, :)
%                 assignin('base','plates_ans', plates_ans);
%                 plate_ans(ep)=plates_ans(ep, :);
 
                  
    %MAke well figure for selecting EXPERIMENTAL GROUP wells                             
    exp_grp_fig{ep} = uipanel(janela,'Visible','on',...
                  'Position',[.52 1-h_val .45 .9/(exp_grp_num)]);
    panAxis = axes('Parent', exp_grp_fig{ep});
              
        set (0, 'DefaultUIControlFontSize', 14-(0.5*exp_grp_num));
                  uicontrol(exp_grp_fig{ep},...
                      'Style','text',...
                      'String', ['Click on "Group #' num2str(ep) '" wells'],...
                      'ForegroundColor',[1 0 .3],...
                      'Units', 'normalized',...
                      'Position',[.01 .005 .25 1]);


        well_IMG = imread(['wells_imgs/' num2str(wells_tot_num) '.tif']);


        plate_IMG{ep} = imshow(well_IMG, 'Border','tight','Parent', panAxis);

        h_val = h_val + .9/(exp_grp_num);
    
        wellClickSelector(wells, plate_IMG{ep}, descr_ans{ep}, plates_ans, plate, ep, wells_tot_num, exp_grp_num, exp_grp_fig{ep});
              
end;

set (0, 'DefaultUIControlFontSize', 25-(0.8*exp_grp_num));
              %SUBMIT button
              submit_button = uicontrol(janela,'Style','pushbutton',...
                  'String','Submit',...
                  'Units', 'normalized',...
                  'Position',[.45 .04 .1 .2/(exp_grp_num)],...
                  'ForegroundColor',[.3 .7 .3],...
                  'Tag', 'submit',...
                  'HandleVisibility','off',...
                  'Callback', {@resume});

waitfor(janela);
    function resume(hObject,eventdata)
        close (janela);
    end
end





